version: "3.8"
  
services:
           
  rabbitmq: 
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports: [5672:5672, 15672:15672]
    volumes: [desafio:/var/lib/rabbitmq] 

volumes: { desafio_rabbitmq: }
  
networks: { net: { driver: bridge } }