version: "3.8"
  
services:      
  sqlserver: 
    user: root
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest 
    volumes: [desafio_db:/var/opt/mssql/data]
    ports: [1433:1433]
    networks: [default]
    environment:
      MSSQL_USER: "SA"
      MSSQL_DATABASE: "desafio"
      MSSQL_DATABASE_COLLATE: "SQL_Latin1_General_CP1_CI_AI"
      MSSQL_PASSWORD: "P4ssw0rd"
      SA_PASSWORD: "P4ssw0rd"
      ACCEPT_EULA: "Y"
            
  mongodb: 
    image: mongo
    container_name: mongodb
    ports: [27017:27017]
    volumes: [desafio_db:/data/db]   
    
volumes: { desafio_db: }
  
networks: { default: { driver: bridge } }