version: "3.8"
  
services:
  sqlserver: 
    user: root
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest 
    volumes: [desafio:/var/opt/mssql/data]
    ports: [1433:1433]
    networks: [net]
    environment:
      MSSQL_USER: "SA"
      MSSQL_DATABASE: "desafio"
      MSSQL_DATABASE_COLLATE: "SQL_Latin1_General_CP1_CI_AI"
      MSSQL_PASSWORD: "P4ssw0rd"
      SA_PASSWORD: "P4ssw0rd"
      ACCEPT_EULA: "Y"
      
volumes: { desafio: }  

networks: { net: { driver: bridge } }