version: "3.8"
  
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
      --require_secure_transport=off
      --lower-case-table-names=1
      --performance_schema
      --authentication-policy='*'
      --bind-address=0.0.0.0
    environment:
      MYSQL_USER: SA
      MYSQL_DATABASE: desafio
      MYSQL_PASSWORD: P4ssw0rd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_PORT: 3306
    ports: [3306:3306]
    networks: [net]
    expose: [3306]
    volumes: 
      - desafio:/var/lib/mysql
      - /desafio:/etc/mysql/conf.d
      
volumes: { desafio: }
  
networks: { net: { driver: bridge } }